package com.github.knives.dojo.problem;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1,2,3,5,8,13,21,34,55,89,⋯
 * By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
 *
 * Constraints
 * 10 <= N <= 4×10^16
 */
public interface EvenFibonacci {
    public static long sum(long n) {
        if (n < 2) {
            return 0;
        }

        long result = 0;

        if (n >= 2) {
            result += 2;
        }

        long[] fib = new long[2];
        fib[0] = 1;
        fib[1] = 2;

        for (int i = 0; true; i = (i+1) % 2 ) {
            fib[i] = fib[0] + fib[1];
            if (fib[i] > n) {
                break;
            }

            if (fib[i] % 2 == 0) {
                result += fib[i];
            }
        }

        return result;
    }
}
